name: Publish to PyPI

on:
  push:
    tags:
      - 'v*.*.*'  # Match tags like v1.0.0, v2.1.3, etc.
      - '[0-9]+.[0-9]+.[0-9]+'  # Match tags like 1.0.0, 2.1.3, etc.  

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: release
      url: https://pypi.org/project/slice-score/
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build

    - name: Build package
      run: |
        python -m build

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      # Use trusted publishing (no API token required)
      # Configure this in PyPI: https://pypi.org/manage/account/publishing/